//! Port of `ichiran/characters:*kana-characters*`
//! (`characters.lisp:11-30`).
//!
//! All regular morae — vowels, k/s/t/n/h/m/y/r/w-rows, `n`, the voiced
//! and semi-voiced rows, and `vu`. 74 entries. Each value pairs the
//! hiragana glyph with the katakana glyph in that order.

use super::kani_kana_class::KanaClass;

pub static KANA_CHARACTERS: &[(KanaClass, &str)] = &[
    (KanaClass::A, "あア"),
    (KanaClass::I, "いイ"),
    (KanaClass::U, "うウ"),
    (KanaClass::E, "えエ"),
    (KanaClass::O, "おオ"),
    (KanaClass::Ka, "かカ"),
    (KanaClass::Ki, "きキ"),
    (KanaClass::Ku, "くク"),
    (KanaClass::Ke, "けケ"),
    (KanaClass::Ko, "こコ"),
    (KanaClass::Sa, "さサ"),
    (KanaClass::Shi, "しシ"),
    (KanaClass::Su, "すス"),
    (KanaClass::Se, "せセ"),
    (KanaClass::So, "そソ"),
    (KanaClass::Ta, "たタ"),
    (KanaClass::Chi, "ちチ"),
    (KanaClass::Tsu, "つツ"),
    (KanaClass::Te, "てテ"),
    (KanaClass::To, "とト"),
    (KanaClass::Na, "なナ"),
    (KanaClass::Ni, "にニ"),
    (KanaClass::Nu, "ぬヌ"),
    (KanaClass::Ne, "ねネ"),
    (KanaClass::No, "のノ"),
    (KanaClass::Ha, "はハ"),
    (KanaClass::Hi, "ひヒ"),
    (KanaClass::Fu, "ふフ"),
    (KanaClass::He, "へヘ"),
    (KanaClass::Ho, "ほホ"),
    (KanaClass::Ma, "まマ"),
    (KanaClass::Mi, "みミ"),
    (KanaClass::Mu, "むム"),
    (KanaClass::Me, "めメ"),
    (KanaClass::Mo, "もモ"),
    (KanaClass::Ya, "やヤ"),
    (KanaClass::Yu, "ゆユ"),
    (KanaClass::Yo, "よヨ"),
    (KanaClass::Ra, "らラ"),
    (KanaClass::Ri, "りリ"),
    (KanaClass::Ru, "るル"),
    (KanaClass::Re, "れレ"),
    (KanaClass::Ro, "ろロ"),
    (KanaClass::Wa, "わワ"),
    (KanaClass::Wi, "ゐヰ"),
    (KanaClass::We, "ゑヱ"),
    (KanaClass::Wo, "をヲ"),
    (KanaClass::N, "んン"),
    (KanaClass::Ga, "がガ"),
    (KanaClass::Gi, "ぎギ"),
    (KanaClass::Gu, "ぐグ"),
    (KanaClass::Ge, "げゲ"),
    (KanaClass::Go, "ごゴ"),
    (KanaClass::Za, "ざザ"),
    (KanaClass::Ji, "じジ"),
    (KanaClass::Zu, "ずズ"),
    (KanaClass::Ze, "ぜゼ"),
    (KanaClass::Zo, "ぞゾ"),
    (KanaClass::Da, "だダ"),
    (KanaClass::Dji, "ぢヂ"),
    (KanaClass::Dzu, "づヅ"),
    (KanaClass::De, "でデ"),
    (KanaClass::Do, "どド"),
    (KanaClass::Ba, "ばバ"),
    (KanaClass::Bi, "びビ"),
    (KanaClass::Bu, "ぶブ"),
    (KanaClass::Be, "べベ"),
    (KanaClass::Bo, "ぼボ"),
    (KanaClass::Pa, "ぱパ"),
    (KanaClass::Pi, "ぴピ"),
    (KanaClass::Pu, "ぷプ"),
    (KanaClass::Pe, "ぺペ"),
    (KanaClass::Po, "ぽポ"),
    (KanaClass::Vu, "ゔヴ"),
];
