//! Rust-only sidecar within the `ichiran/characters` port module.
//! Has no Lisp counterpart.
//!
//! `KanaClass` is the closed enumeration of the 87 mora / modifier /
//! iteration tags that categorize a single kana glyph. The upstream
//! uses keyword symbols (`:A`, `:KA`, `:SOKUON`, `:+YA`, `:LONG-VOWEL`,
//! …) inline without a named type.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum KanaClass {
    Sokuon,
    Iter,
    IterV,
    PlusA,
    PlusI,
    PlusU,
    PlusE,
    PlusO,
    PlusYa,
    PlusYu,
    PlusYo,
    PlusWa,
    LongVowel,
    A,
    I,
    U,
    E,
    O,
    Ka,
    Ki,
    Ku,
    Ke,
    Ko,
    Sa,
    Shi,
    Su,
    Se,
    So,
    Ta,
    Chi,
    Tsu,
    Te,
    To,
    Na,
    Ni,
    Nu,
    Ne,
    No,
    Ha,
    Hi,
    Fu,
    He,
    Ho,
    Ma,
    Mi,
    Mu,
    Me,
    Mo,
    Ya,
    Yu,
    Yo,
    Ra,
    Ri,
    Ru,
    Re,
    Ro,
    Wa,
    Wi,
    We,
    Wo,
    N,
    Ga,
    Gi,
    Gu,
    Ge,
    Go,
    Za,
    Ji,
    Zu,
    Ze,
    Zo,
    Da,
    Dji,
    Dzu,
    De,
    Do,
    Ba,
    Bi,
    Bu,
    Be,
    Bo,
    Pa,
    Pi,
    Pu,
    Pe,
    Po,
    Vu,
}

impl KanaClass {
    /// The upstream Lisp keyword's printed name: `Ka` → `"KA"`,
    /// `PlusYa` → `"+YA"`, `LongVowel` → `"LONG-VOWEL"`, `IterV` →
    /// `"ITER-V"`.
    pub fn lisp_name(&self) -> &'static str {
        match self {
            KanaClass::Sokuon => "SOKUON",
            KanaClass::Iter => "ITER",
            KanaClass::IterV => "ITER-V",
            KanaClass::PlusA => "+A",
            KanaClass::PlusI => "+I",
            KanaClass::PlusU => "+U",
            KanaClass::PlusE => "+E",
            KanaClass::PlusO => "+O",
            KanaClass::PlusYa => "+YA",
            KanaClass::PlusYu => "+YU",
            KanaClass::PlusYo => "+YO",
            KanaClass::PlusWa => "+WA",
            KanaClass::LongVowel => "LONG-VOWEL",
            KanaClass::A => "A",
            KanaClass::I => "I",
            KanaClass::U => "U",
            KanaClass::E => "E",
            KanaClass::O => "O",
            KanaClass::Ka => "KA",
            KanaClass::Ki => "KI",
            KanaClass::Ku => "KU",
            KanaClass::Ke => "KE",
            KanaClass::Ko => "KO",
            KanaClass::Sa => "SA",
            KanaClass::Shi => "SHI",
            KanaClass::Su => "SU",
            KanaClass::Se => "SE",
            KanaClass::So => "SO",
            KanaClass::Ta => "TA",
            KanaClass::Chi => "CHI",
            KanaClass::Tsu => "TSU",
            KanaClass::Te => "TE",
            KanaClass::To => "TO",
            KanaClass::Na => "NA",
            KanaClass::Ni => "NI",
            KanaClass::Nu => "NU",
            KanaClass::Ne => "NE",
            KanaClass::No => "NO",
            KanaClass::Ha => "HA",
            KanaClass::Hi => "HI",
            KanaClass::Fu => "FU",
            KanaClass::He => "HE",
            KanaClass::Ho => "HO",
            KanaClass::Ma => "MA",
            KanaClass::Mi => "MI",
            KanaClass::Mu => "MU",
            KanaClass::Me => "ME",
            KanaClass::Mo => "MO",
            KanaClass::Ya => "YA",
            KanaClass::Yu => "YU",
            KanaClass::Yo => "YO",
            KanaClass::Ra => "RA",
            KanaClass::Ri => "RI",
            KanaClass::Ru => "RU",
            KanaClass::Re => "RE",
            KanaClass::Ro => "RO",
            KanaClass::Wa => "WA",
            KanaClass::Wi => "WI",
            KanaClass::We => "WE",
            KanaClass::Wo => "WO",
            KanaClass::N => "N",
            KanaClass::Ga => "GA",
            KanaClass::Gi => "GI",
            KanaClass::Gu => "GU",
            KanaClass::Ge => "GE",
            KanaClass::Go => "GO",
            KanaClass::Za => "ZA",
            KanaClass::Ji => "JI",
            KanaClass::Zu => "ZU",
            KanaClass::Ze => "ZE",
            KanaClass::Zo => "ZO",
            KanaClass::Da => "DA",
            KanaClass::Dji => "DJI",
            KanaClass::Dzu => "DZU",
            KanaClass::De => "DE",
            KanaClass::Do => "DO",
            KanaClass::Ba => "BA",
            KanaClass::Bi => "BI",
            KanaClass::Bu => "BU",
            KanaClass::Be => "BE",
            KanaClass::Bo => "BO",
            KanaClass::Pa => "PA",
            KanaClass::Pi => "PI",
            KanaClass::Pu => "PU",
            KanaClass::Pe => "PE",
            KanaClass::Po => "PO",
            KanaClass::Vu => "VU",
        }
    }
}
