//! Rust-only sidecar within the `ichiran/characters` port module.
//! Has no Lisp counterpart.
//!
//! `KanaClass` is the closed enumeration of the 87 mora / modifier /
//! iteration tags that categorize a single kana glyph. The upstream
//! uses keyword symbols (`:A`, `:KA`, `:SOKUON`, `:+YA`, `:LONG-VOWEL`,
//! …) inline at hundreds of callsites without a named type — the tag
//! set is implicitly defined by the keys of `*all-characters*` plus
//! the same-shape `eql` callsites in `romanize.lisp` and `dict.lisp`.
//!
//! Naming convention: `kani_<snake_name>.rs` marks a Rust-only
//! sidecar, distinguishing it from `_star_<name>_star_.rs` (global
//! ports) and `<name>_<kind>.rs` (typed-Lisp ports).

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum KanaClass {
    Sokuon,
    Iter,
    IterV,
    PlusA,
    PlusI,
    PlusU,
    PlusE,
    PlusO,
    PlusYa,
    PlusYu,
    PlusYo,
    PlusWa,
    LongVowel,
    A,
    I,
    U,
    E,
    O,
    Ka,
    Ki,
    Ku,
    Ke,
    Ko,
    Sa,
    Shi,
    Su,
    Se,
    So,
    Ta,
    Chi,
    Tsu,
    Te,
    To,
    Na,
    Ni,
    Nu,
    Ne,
    No,
    Ha,
    Hi,
    Fu,
    He,
    Ho,
    Ma,
    Mi,
    Mu,
    Me,
    Mo,
    Ya,
    Yu,
    Yo,
    Ra,
    Ri,
    Ru,
    Re,
    Ro,
    Wa,
    Wi,
    We,
    Wo,
    N,
    Ga,
    Gi,
    Gu,
    Ge,
    Go,
    Za,
    Ji,
    Zu,
    Ze,
    Zo,
    Da,
    Dji,
    Dzu,
    De,
    Do,
    Ba,
    Bi,
    Bu,
    Be,
    Bo,
    Pa,
    Pi,
    Pu,
    Pe,
    Po,
    Vu,
}
