#!/usr/bin/env python3
"""
Parse the auto-generated *.md files under reverse/ into two normalized CSVs:

  symbols.csv  fqn, name, package, file, line, kind, status, reason,
               extracted, audited
  edges.csv    caller_fqn, callee_fqn, resolved, origin

The `reason` column captures *why* a symbol is off-the-books (e.g. why a
`skip` was chosen over `pending`). Free-form text; empty for pending /
ported rows. build_graph.py wipes both `status` and `reason` on every
run — commit symbols.csv first or re-record via `query.py mark --reason`.

The `extracted` and `audited` columns track parallel workstreams and
survive build_graph.py rebuilds — they reflect on-disk parquet artifacts
and audit-binary results that don't change just because the introspector
reran:

  extracted  which extraction driver produced fixtures for this fn
             (e.g. "tatoeba", "init-suffixes", "conj-probe"). Set by
             `query.py extracted`.
  audited    pass-rate from the canonical
                tatoeba → parquet → audit_fixtures / audit_dict_fixtures
             pipeline. RESERVED for that pipeline only — captures from
             non-tatoeba drivers (init-suffixes, synthetic probes,
             one-shot scripts) get `extracted` but never `audited`.
             Format "P/T" (or "P/T (F fail)" if P < T). Set by
             `query.py audited`.

Populator ports (no-conj-data, is-arch, counter-cache, suffix-cache,
init-suffixes-thread, etc.) are verified via cache-cardinality
cross-check (`cache_inspect`); their `extracted` / `audited` columns
stay empty.

The `origin` column on edges.csv records which extraction pass found the
edge: `runtime` (SBCL who-calls — function-call edges only), `source`
(introspector's source-walk pass — catches data references like quoted
DAO-class symbols passed to postmodern helpers), `structural` (synthesized
from defstruct metadata: edges from each compiler-generated companion —
constructor, predicate, copier, accessors — back to its owning struct,
since SBCL's source-walker can't see the bodies of these autogenerated
fns), or `both` (runtime ∩ source).

Recognised md kinds (by filename suffix):
  *.md            function / macro / generic   — dependency = "## Dependencies"
                                                 + "## Source-walked references"
  *_struct.md     defstruct                    — dependency = :include parent struct
                                                 + structural edges from the
                                                   constructor / predicate /
                                                   copier / accessors back to
                                                   the struct
  *_class.md      defclass                     — dependency = direct superclasses
  *_dao.md        defclass :metaclass dao-class — dependency = direct superclasses
  *_global.md     defparameter / defvar / defconstant
                                               — dependency = symbol references
                                                 inside the printed value block
  *_type.md       deftype                      — dependency = members referenced
  *_condition.md  define-condition             — dependency = inherited condition

Run from repo root:
    python3 reverse/scripts/build_graph.py
"""
from __future__ import annotations

import csv
import json
import os
import re
import sys
from pathlib import Path

REVERSE_DIR = Path(__file__).resolve().parent.parent
OUT_DIR = REVERSE_DIR / "scripts"
SYMBOLS_CSV = OUT_DIR / "symbols.csv"
EDGES_CSV = OUT_DIR / "edges.csv"
SIGNATURES_JSON = OUT_DIR / "signatures.json"

# H1 forms:
#   "# kr-canonical"
#   "# kana-representation (defstruct)"
#   "# *sokuon-characters* (global variable)"
H1 = re.compile(r"^#\s+(\S.*?)(?:\s+\([^)]+\))?\s*$")
PACKAGE = re.compile(r"^\*\*Package:\*\*\s+`([^`]+)`")
SOURCE = re.compile(r"^\*\*Source:\*\*\s+`([^`:]+)(?::(\d+))?`")
DEFFORM = re.compile(r"^\*\*Definition form:\*\*\s+`([^`]+)`")
DEP = re.compile(r"^- `([^`]+)`")
DEP_HEADER = re.compile(r"^##\s+Dependencies")
SOURCE_WALK_HEADER = re.compile(r"^##\s+Source-walked references")

INCLUDE = re.compile(r"^\*\*Include:\*\*\s+`([^`]+)`")
INHERITS = re.compile(r"^\*\*Inherits:\*\*\s+`([^`]+)`")
SUPERS = re.compile(r"^- Direct supers:\s+(.+)$")
TICK = re.compile(r"`([^`]+)`")
VALUE_FENCE = re.compile(r"^```")

# Defstruct-companion line scrapers. Each captures a single backticked symbol
# (NIL means the option was suppressed; we filter that out before resolving).
STRUCT_DEFAULT_CTOR = re.compile(r"^\*\*Default constructor:\*\*\s+`([^`]+)`")
STRUCT_PREDICATE = re.compile(r"^\*\*Predicate:\*\*\s+`([^`]+)`")
STRUCT_COPIER = re.compile(r"^\*\*Copier:\*\*\s+`([^`]+)`")
# `**All constructors:**` may span multiple lines (BOA constructors with slot
# lists). Match the first line; we accumulate text until we see the closing
# backtick.
STRUCT_ALL_CTORS_HEAD = re.compile(r"^\*\*All constructors:\*\*\s+`(.*)$")
STRUCT_SLOTS_HEADER = re.compile(r"^##\s+Slots\s*$")
# Slot table row: 4th column is the accessor (backticked symbol or `nil`).
STRUCT_SLOT_ROW = re.compile(r"^\|\s*[^|]+\|\s*[^|]+\|\s*[^|]+\|\s*([^|]+?)\s*\|")
# Inside the All-constructors blob: any package-qualified or bare `make-…`
# symbol. Case-insensitive (sb-kernel prints constructor names lowercase via
# `~(~s~)`, but we match either form for safety).
STRUCT_MAKE_REF = re.compile(
    r"\b((?:[A-Za-z0-9/_+*-]+::?)?make-[A-Za-z0-9/_+*-]+)\b",
    re.IGNORECASE,
)
# Symbol mention inside a value block, e.g. ICHIRAN/DICT::ABBR-II
SYMBOL_REF = re.compile(r"ICHIRAN(?:/[A-Z0-9-]+)?::?[A-Z0-9*+/_-]+")

KIND_MAP = {"defun": "fn", "defmacro": "macro", "defgeneric": "gf"}

# Suffix → kind label written into symbols.csv. Order matters for
# longest-match (none collide here, but keep explicit for clarity).
SUFFIX_KIND = [
    ("_struct.md", "struct"),
    ("_class.md", "class"),
    ("_dao.md", "dao"),
    ("_global.md", "global"),
    ("_type.md", "type"),
    ("_condition.md", "condition"),
]


def fqn(package: str, name: str) -> str:
    return f"{package}:{name}"


def split_dep(token: str) -> tuple[str, str]:
    """`ichiran/characters:test-word` or `ichiran::strings` → (package, name)."""
    if "::" in token:
        pkg, _, name = token.partition("::")
    else:
        pkg, _, name = token.partition(":")
    return pkg, name


def normalise_dep(token: str) -> str:
    """Lowercase the package and name for consistent CSV joining."""
    pkg, name = split_dep(token.strip("`"))
    return fqn(pkg.lower(), name.lower())


def aux_kind(path: Path) -> str | None:
    name = path.name
    for suffix, kind in SUFFIX_KIND:
        if name.endswith(suffix):
            return kind
    return None


SECTION_HEADER = re.compile(r"^##\s+")
INPUTS_HEADER = re.compile(r"^##\s+Inputs\b")
OUTPUTS_HEADER = re.compile(r"^##\s+Outputs\b")
DECLARED_FTYPE = re.compile(r"^Declared ftype:\s*`(.+)`\s*$", re.DOTALL)
DOCSTRING_LINE = re.compile(r"^Docstring:\s*(.+)$", re.DOTALL)


def collect_section(lines: list[str], header_idx: int) -> str:
    """Return the section body (lines after `## Header`, up to the next `## `),
    joined with newlines and stripped."""
    j = header_idx + 1
    body: list[str] = []
    while j < len(lines) and not SECTION_HEADER.match(lines[j]):
        body.append(lines[j])
        j += 1
    return "\n".join(body).strip()


def collapse_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()


def parse_signature(raw_lines: list[str]) -> dict | None:
    """Extract the lambda list / declared ftype / docstring from an md file.

    Returns a dict with keys `lambda_list` (str | None), `ftype` (str | None),
    `docstring` (str | None), or `None` if the md file has no signature
    sections at all (struct / class / dao / global / type / condition).

    Whitespace inside the lambda list and ftype is collapsed to single spaces
    so the output is byte-stable across re-runs of the introspector.
    """
    lambda_list: str | None = None
    ftype: str | None = None
    docstring: str | None = None

    for i, line in enumerate(raw_lines):
        if INPUTS_HEADER.match(line):
            body = collect_section(raw_lines, i)
            if body.startswith("`") and body.endswith("`") and len(body) > 1:
                lambda_list = collapse_ws(body[1:-1])
        elif OUTPUTS_HEADER.match(line):
            body = collect_section(raw_lines, i)
            m = DECLARED_FTYPE.match(body)
            if m:
                ftype = collapse_ws(m.group(1))
            else:
                m = DOCSTRING_LINE.match(body)
                if m:
                    docstring = collapse_ws(m.group(1))

    if lambda_list is None and ftype is None and docstring is None:
        return None
    return {"lambda_list": lambda_list, "ftype": ftype, "docstring": docstring}


def _norm_companion(token: str, package: str) -> str | None:
    """Normalize one defstruct-companion symbol (constructor / predicate /
    copier / accessor) to a lowercased FQN. Returns None for NIL / blank
    (suppressed options) so the caller can skip them."""
    n = token.strip().strip("`").strip()
    if not n or n.upper() == "NIL":
        return None
    if "::" in n or ":" in n:
        return normalise_dep(n)
    return normalise_dep(f"{package}:{n}")


def parse_struct_spawned(raw_lines: list[str], package: str) -> list[str]:
    """Extract every symbol the defstruct *spawns* (default + BOA
    constructors, predicate, copier, slot accessors).

    Returns deduplicated FQNs in declaration order. Used to synthesize
    `companion → struct` edges that SBCL's source-walker can't produce
    on its own (the bodies of these compiler-generated fns aren't visible
    to `function-lambda-expression`)."""
    out: list[str] = []
    seen: set[str] = set()

    def add(fq: str | None) -> None:
        if fq is not None and fq not in seen:
            seen.add(fq)
            out.append(fq)

    in_all_ctors = False
    all_ctors_buf: list[str] = []
    in_slots = False

    for line in raw_lines:
        if in_all_ctors:
            all_ctors_buf.append(line)
            if "`" in line:
                in_all_ctors = False
            continue

        m = STRUCT_DEFAULT_CTOR.match(line)
        if m:
            add(_norm_companion(m.group(1), package))
            continue
        m = STRUCT_PREDICATE.match(line)
        if m:
            add(_norm_companion(m.group(1), package))
            continue
        m = STRUCT_COPIER.match(line)
        if m:
            add(_norm_companion(m.group(1), package))
            continue
        m = STRUCT_ALL_CTORS_HEAD.match(line)
        if m:
            head = m.group(1)
            all_ctors_buf.append(head)
            # The head line may already contain the closing backtick.
            if "`" in head:
                in_all_ctors = False
            else:
                in_all_ctors = True
            continue

        if STRUCT_SLOTS_HEADER.match(line):
            in_slots = True
            continue
        if in_slots:
            if line.startswith("##"):
                in_slots = False
            else:
                m = STRUCT_SLOT_ROW.match(line)
                if m:
                    cell = m.group(1).strip()
                    if cell.lower() in ("accessor", "---"):
                        continue
                    add(_norm_companion(cell, package))

    # Pick every `make-…` reference out of the (possibly multi-line)
    # All-constructors blob. Catches BOA constructors that aren't in the
    # `Default constructor:` line, e.g. conjugation-rule's
    # `make-conjugation-rule` is declared via `:constructor make-X (...)`
    # with `:default` suppressed.
    blob = "\n".join(all_ctors_buf)
    for m in STRUCT_MAKE_REF.finditer(blob):
        add(_norm_companion(m.group(1), package))

    return out


def parse_value_block_deps(lines: list[str], start_idx: int) -> list[str]:
    """From a ```lisp fenced block, extract every ICHIRAN-package symbol
    reference inside. Returns lowercased FQNs."""
    deps: list[str] = []
    i = start_idx + 1
    while i < len(lines):
        if VALUE_FENCE.match(lines[i]):
            break
        for m in SYMBOL_REF.finditer(lines[i]):
            deps.append(normalise_dep(m.group(0)))
        i += 1
    return deps


def parse_md_header(raw_lines: list[str]) -> tuple[str | None, str | None, str | None, int, str | None]:
    """Parse H1 / Package / Source / Definition-form lines from an md file.

    Returns (name, package, source_file, line_no, kind_field). Any field
    that wasn't found is None (line_no defaults to 0). Used by both
    `parse_md` (which then resolves dependencies) and the signatures
    extractor (which only needs the symbol identity).
    """
    name = package = source_file = kind_field = None
    line_no = 0
    for line in raw_lines:
        if name is None:
            m = H1.match(line)
            if m:
                name = m.group(1).strip()
                continue
        if package is None:
            m = PACKAGE.match(line)
            if m:
                package = m.group(1)
                continue
        if source_file is None:
            m = SOURCE.match(line)
            if m:
                source_file = m.group(1)
                line_no = int(m.group(2)) if m.group(2) else 0
                continue
        if kind_field is None:
            m = DEFFORM.match(line)
            if m:
                kind_field = KIND_MAP.get(m.group(1), m.group(1))
                continue
    return name, package, source_file, line_no, kind_field


def parse_md(path: Path) -> tuple[dict, list[str], list[str], list[str]] | None:
    """Returns ({symbol-row}, [runtime-deps], [source-walk-deps], [structural-spawned]) or None.

    `structural-spawned` is non-empty only for `_struct.md` rows: it lists the
    FQNs the defstruct generates (constructor, predicate, copier, accessors).
    The caller inverts them into `spawned → struct` edges with origin
    'structural', because the spawned fns have no walkable body for
    `function-lambda-expression` to surface a dep on the struct."""
    raw_lines = path.read_text(encoding="utf-8").splitlines()
    deps: list[str] = []
    source_walk_deps: list[str] = []
    structural_spawned: list[str] = []
    in_deps = False

    suffix_kind = aux_kind(path)
    name, package, source_file, line_no, kind_field = parse_md_header(raw_lines)

    if not (name and package):
        return None

    # Second pass: dependency extraction (kind-specific).
    if suffix_kind is None:
        # Functions / macros / generics: two sections.
        # `## Dependencies` is the runtime call-graph (precise per-method when
        # nested under `### method (...)`).
        # `## Source-walked references` is the source-walk pass — catches DAO
        # class symbols and other data references invisible to the call graph.
        in_source_walk = False
        for line in raw_lines:
            if DEP_HEADER.match(line):
                in_deps, in_source_walk = True, False
                continue
            if SOURCE_WALK_HEADER.match(line):
                in_deps, in_source_walk = False, True
                continue
            if in_deps or in_source_walk:
                if line.startswith("## "):
                    in_deps = in_source_walk = False
                    continue
                m = DEP.match(line)
                if m:
                    target = source_walk_deps if in_source_walk else deps
                    target.append(normalise_dep(m.group(1)))
        kind_out = kind_field or ""
    elif suffix_kind in ("struct",):
        for line in raw_lines:
            m = INCLUDE.match(line)
            if m and m.group(1).strip().upper() != "NIL":
                # Bare struct name, e.g. `SOMETHING` — assume same package.
                inc = m.group(1).strip()
                deps.append(normalise_dep(f"{package}:{inc}"))
                break
        structural_spawned = parse_struct_spawned(raw_lines, package)
        kind_out = "struct"
    elif suffix_kind in ("class", "dao"):
        for line in raw_lines:
            m = SUPERS.match(line)
            if m:
                # Pull each backticked symbol; superclasses can be
                # bare (same-package) or fully-qualified.
                for tok in TICK.findall(m.group(1)):
                    if tok.upper() == "STANDARD-OBJECT" or tok.lower() == "_(none)_":
                        continue
                    if ":" in tok:
                        deps.append(normalise_dep(tok))
                    else:
                        deps.append(normalise_dep(f"{package}:{tok}"))
                break
        kind_out = suffix_kind
    elif suffix_kind == "global":
        # Find the ```lisp fence and walk for symbol references.
        for idx, line in enumerate(raw_lines):
            if VALUE_FENCE.match(line) and "lisp" in line:
                deps.extend(parse_value_block_deps(raw_lines, idx))
                break
        kind_out = "global"
    elif suffix_kind == "type":
        # The single deftype in the codebase has no ichiran-symbol deps;
        # walking the value block harmlessly returns nothing.
        for idx, line in enumerate(raw_lines):
            if VALUE_FENCE.match(line) and "lisp" in line:
                deps.extend(parse_value_block_deps(raw_lines, idx))
                break
        kind_out = "type"
    elif suffix_kind == "condition":
        for line in raw_lines:
            m = INHERITS.match(line)
            if m and m.group(1).upper() != "ERROR":
                deps.append(normalise_dep(f"{package}:{m.group(1).strip()}"))
                break
        kind_out = "condition"
    else:
        kind_out = suffix_kind

    # Source-walked references can appear on any md kind — the introspector
    # emits the section for fn/macro/gf, classes/structs/daos/conditions, and
    # globals (the last specifically catches DSL-defined globals like
    # *counter-cache* / *special-counters* whose populator body the call-graph
    # pass can't see). The kind-specific branches above don't consume this
    # section, so we run a unified parse here for kinds that didn't already.
    if suffix_kind is not None:
        in_source_walk = False
        for line in raw_lines:
            if SOURCE_WALK_HEADER.match(line):
                in_source_walk = True
                continue
            if in_source_walk:
                if line.startswith("## "):
                    in_source_walk = False
                    continue
                m = DEP.match(line)
                if m:
                    source_walk_deps.append(normalise_dep(m.group(1)))

    # For defstructs, the source-walker can pick up the constructor / predicate /
    # copier names when they're explicitly written in the `:constructor make-X
    # (...)` / `:predicate ...` / `:copier ...` options, producing `struct →
    # companion` edges that are inverted relative to what the port plan needs.
    # Drop those — the structural pass writes the correct direction.
    if structural_spawned:
        spawn_set = set(structural_spawned)
        source_walk_deps = [d for d in source_walk_deps if d not in spawn_set]
        deps = [d for d in deps if d not in spawn_set]

    return (
        {
            "fqn": fqn(package, name),
            "name": name,
            "package": package,
            "file": source_file or "",
            "line": line_no,
            "kind": kind_out,
            "status": "pending",
            "reason": "",
            "extracted": "",
            "audited": "",
        },
        deps,
        source_walk_deps,
        structural_spawned,
    )


def extract_signatures(md_files: list[Path]) -> dict[str, dict]:
    """Walk md files and pull the lambda list / declared ftype / docstring
    for every fn / macro / gf. Skips kinds that have no callable surface
    (struct / class / dao / global / type / condition).

    Keyed by FQN as derived from the md file's Package + H1 fields. Note:
    the FQN can be wrong if the introspector mislabeled a symbol's package
    (see the `not-a-number` case noted in the gate at __main__) — but that
    bug only affects non-fn kinds, which are skipped here, so signatures.json
    is unpoisoned.
    """
    sigs: dict[str, dict] = {}
    for path in md_files:
        raw_lines = path.read_text(encoding="utf-8").splitlines()
        name, package, source_file, line_no, kind_field = parse_md_header(raw_lines)
        if not (name and package):
            continue
        suffix_kind = aux_kind(path)
        kind = suffix_kind or (kind_field or "")
        sig = parse_signature(raw_lines)
        if sig is None:
            continue
        key = fqn(package, name)
        sigs[key] = {
            "name": name,
            "package": package,
            "file": source_file or "",
            "line": line_no,
            "kind": kind,
            **sig,
        }
    return sigs


def write_signatures(sigs: dict[str, dict]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Sort keys for byte-stable output across runs.
    payload = {k: sigs[k] for k in sorted(sigs)}
    SIGNATURES_JSON.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def signatures_only() -> int:
    md_files = sorted(REVERSE_DIR.glob("*.lisp/*.md"))
    if not md_files:
        print(f"no md files under {REVERSE_DIR}", file=sys.stderr)
        return 1
    sigs = extract_signatures(md_files)
    write_signatures(sigs)
    rel = lambda p: os.path.relpath(p, REVERSE_DIR.parent)
    print(f"signatures: {len(sigs)} -> {rel(SIGNATURES_JSON)}")
    return 0


def main() -> int:
    md_files = sorted(REVERSE_DIR.glob("*.lisp/*.md"))
    if not md_files:
        print(f"no md files under {REVERSE_DIR}", file=sys.stderr)
        return 1

    rows: list[dict] = []
    runtime_pending: list[tuple[str, str]] = []
    source_pending: list[tuple[str, str]] = []
    structural_pending: list[tuple[str, str]] = []
    seen: set[str] = set()

    for path in md_files:
        parsed = parse_md(path)
        if parsed is None:
            print(f"skip (no header): {path}", file=sys.stderr)
            continue
        sym, deps, swdeps, spawned = parsed
        # If the same fqn appears via both a function md and a struct md
        # (e.g. autogenerated accessor + struct itself collide), keep the
        # first one encountered alphabetically and warn. In practice the
        # struct/class fqns are distinct from their accessor fqns so this
        # only fires on real duplicates.
        if sym["fqn"] in seen:
            print(
                f"duplicate fqn: {sym['fqn']} (skipping {path.name})",
                file=sys.stderr,
            )
            continue
        seen.add(sym["fqn"])
        rows.append(sym)
        for dep in deps:
            runtime_pending.append((sym["fqn"], dep))
        for dep in swdeps:
            source_pending.append((sym["fqn"], dep))
        # Structural edges run companion → struct. The defstruct itself is
        # `sym["fqn"]`, the spawned companions are `spawned`.
        for spawn in spawned:
            structural_pending.append((spawn, sym["fqn"]))

    by_fqn = {r["fqn"]: r for r in rows}

    # Source-walk over-collects (locals, lambda-list params, slot names).
    # Drop callees that aren't a known top-level definition. Self-edges
    # (introspector also filters them but belt-and-suspenders) get dropped.
    source_filtered: list[tuple[str, str]] = []
    source_dropped = 0
    for caller, callee in source_pending:
        if callee not in by_fqn or callee == caller:
            source_dropped += 1
            continue
        source_filtered.append((caller, callee))

    # Structural edges (companion → struct) — drop any that point at an
    # unknown caller (companion might be filtered out of the universe by
    # has-any-definition-p) or that are self-referential.
    structural_filtered: list[tuple[str, str]] = []
    structural_dropped = 0
    for caller, callee in structural_pending:
        if caller not in by_fqn or caller == callee:
            structural_dropped += 1
            continue
        structural_filtered.append((caller, callee))

    # Union with origin tagging. Structural edges win over runtime / source
    # tags when present — they describe a different relationship (companion
    # → owner) that the other passes can't see, and we want them surfaced
    # explicitly in the `origin` column for traceability.
    runtime_set = set(runtime_pending)
    source_set = set(source_filtered)
    structural_set = set(structural_filtered)
    edges: list[tuple[str, str, int, str]] = []
    unresolved: set[str] = set()
    seen_pairs: set[tuple[str, str]] = set()
    runtime_only = 0
    source_only = 0
    structural_only = 0
    both_count = 0
    for caller, callee in sorted(runtime_set | source_set | structural_set):
        if (caller, callee) in seen_pairs:
            continue
        seen_pairs.add((caller, callee))
        in_structural = (caller, callee) in structural_set
        in_runtime = (caller, callee) in runtime_set
        in_source = (caller, callee) in source_set
        if in_structural:
            origin = "structural"
            structural_only += 1
        elif in_runtime and in_source:
            origin = "both"
            both_count += 1
        elif in_source:
            origin = "source"
            source_only += 1
        else:
            origin = "runtime"
            runtime_only += 1
        resolved = 1 if callee in by_fqn else 0
        if not resolved:
            unresolved.add(callee)
        edges.append((caller, callee, resolved, origin))

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Preserve `extracted` / `audited` across rebuilds — they reflect
    # parquet artifacts on disk + audit-binary runs that don't change
    # when the introspector reruns. `status` and `reason` still reset
    # per the documented behaviour at the top of this file.
    prior_workstream: dict[str, dict[str, str]] = {}
    if SYMBOLS_CSV.exists():
        with SYMBOLS_CSV.open(encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                prior_workstream[r["fqn"]] = {
                    "extracted": r.get("extracted", "") or "",
                    "audited":   r.get("audited", "")   or "",
                }

    fieldnames = [
        "fqn", "name", "package", "file", "line", "kind",
        "status", "reason", "extracted", "audited",
    ]
    with SYMBOLS_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fieldnames)
        w.writeheader()
        for r in sorted(rows, key=lambda r: r["fqn"]):
            prior = prior_workstream.get(r["fqn"], {})
            r["extracted"] = prior.get("extracted", "")
            r["audited"]   = prior.get("audited", "")
            w.writerow(r)

    with EDGES_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["caller_fqn", "callee_fqn", "resolved", "origin"])
        for row in sorted(edges):
            w.writerow(row)

    sigs = extract_signatures(md_files)
    write_signatures(sigs)

    rel = lambda p: os.path.relpath(p, REVERSE_DIR.parent)
    print(f"symbols: {len(rows)} -> {rel(SYMBOLS_CSV)}")
    print(f"edges:   {len(edges)} -> {rel(EDGES_CSV)}")
    print(f"signatures: {len(sigs)} -> {rel(SIGNATURES_JSON)}")
    print(
        f"  origin: runtime={runtime_only}, source={source_only}, "
        f"structural={structural_only}, both={both_count} "
        f"(source-walk dropped {source_dropped} non-top-level / self refs; "
        f"structural dropped {structural_dropped})"
    )
    if unresolved:
        print(f"unresolved callees: {len(unresolved)} (external / built-in)")

    # Per-kind breakdown for sanity.
    from collections import Counter
    kinds = Counter(r["kind"] for r in rows)
    print(
        "by kind: "
        + ", ".join(f"{k}={n}" for k, n in sorted(kinds.items(), key=lambda x: -x[1]))
    )
    return 0


if __name__ == "__main__":
    if "--signatures-only" in sys.argv[1:]:
        sys.exit(signatures_only())
    sys.exit(main())
