#!/usr/bin/env python3
"""
Parse the auto-generated *.md files under reverse/ into two normalized CSVs:

  symbols.csv  fqn, name, package, file, line, kind, status, reason,
               extracted, audited
  edges.csv    caller_fqn, callee_fqn, resolved, origin

The `reason` column captures *why* a symbol is off-the-books (e.g. why a
`skip` was chosen over `pending`). Free-form text; empty for pending /
ported rows.

build_graph.py preserves all four state columns (`status`, `reason`,
`extracted`, `audited`) across rebuilds. They reflect porter / pipeline
state, not introspector output, and have no reason to reset just because
the graph regenerated. Symbols that disappear between runs lose their
state (no row to hold it); new symbols start with empty state.

The `extracted` and `audited` columns track parallel workstreams and
survive build_graph.py rebuilds — they reflect on-disk parquet artifacts
and audit-binary results that don't change just because the introspector
reran:

  extracted  which extraction driver produced fixtures for this fn
             (e.g. "tatoeba", "init-suffixes", "conj-probe"). Set by
             `query.py extracted`.
  audited    pass-rate from the canonical
                tatoeba → parquet → audit_fixtures / audit_dict_fixtures
             pipeline. RESERVED for that pipeline only — captures from
             non-tatoeba drivers (init-suffixes, synthetic probes,
             one-shot scripts) get `extracted` but never `audited`.
             Format "P/T" (or "P/T (F fail)" if P < T). Set by
             `query.py audited`.

Populator ports (no-conj-data, is-arch, counter-cache, suffix-cache,
init-suffixes-thread, etc.) are verified via cache-cardinality
cross-check (`cache_inspect`); their `extracted` / `audited` columns
stay empty.

The `origin` column on edges.csv records which extraction pass found the
edge: `runtime` (SBCL who-calls — function-call edges only), `source`
(introspector's source-walk pass — catches data references like quoted
DAO-class symbols passed to postmodern helpers), `structural` (synthesized
from defstruct metadata: edges from each compiler-generated companion —
constructor, predicate, copier, accessors — back to its owning struct,
since SBCL's source-walker can't see the bodies of these autogenerated
fns), `slot-type` (synthesized from `slot_types.csv` — hand-curated
edges from a defstruct to the type held in each of its `t`-typed slots,
since the introspector can't recover the slot's value type from a `t`
declaration), or `both` (runtime ∩ source).

Recognised md kinds (by filename suffix):
  *.md            function / macro / generic   — dependency = "## Dependencies"
                                                 + "## Source-walked references"
  *_struct.md     defstruct                    — dependency = :include parent struct
                                                 + structural edges from the
                                                   constructor / predicate /
                                                   copier / accessors back to
                                                   the struct
  *_class.md      defclass                     — dependency = direct superclasses
  *_dao.md        defclass :metaclass dao-class — dependency = direct superclasses
  *_global.md     defparameter / defvar / defconstant
                                               — dependency = symbol references
                                                 inside the printed value block
  *_type.md       deftype                      — dependency = members referenced
  *_condition.md  define-condition             — dependency = inherited condition

Run from repo root:
    python3 reverse/scripts/build_graph.py
"""
from __future__ import annotations

import csv
import json
import os
import re
import sys
from pathlib import Path

REVERSE_DIR = Path(__file__).resolve().parent.parent
OUT_DIR = REVERSE_DIR / "scripts"
SYMBOLS_CSV = OUT_DIR / "symbols.csv"
EDGES_CSV = OUT_DIR / "edges.csv"
SIGNATURES_JSON = OUT_DIR / "signatures.json"
SLOT_TYPES_CSV = OUT_DIR / "slot_types.csv"

# H1 forms:
#   "# kr-canonical"
#   "# kana-representation (defstruct)"
#   "# *sokuon-characters* (global variable)"
H1 = re.compile(r"^#\s+(\S.*?)(?:\s+\([^)]+\))?\s*$")
PACKAGE = re.compile(r"^\*\*Package:\*\*\s+`([^`]+)`")
SOURCE = re.compile(r"^\*\*Source:\*\*\s+`([^`:]+)(?::(\d+))?`")
DEFFORM = re.compile(r"^\*\*Definition form:\*\*\s+`([^`]+)`")
DEP = re.compile(r"^- `([^`]+)`")
DEP_HEADER = re.compile(r"^##\s+Dependencies")
SOURCE_WALK_HEADER = re.compile(r"^##\s+Source-walked references")

INCLUDE = re.compile(r"^\*\*Include:\*\*\s+`([^`]+)`")
INHERITS = re.compile(r"^\*\*Inherits:\*\*\s+`([^`]+)`")
SUPERS = re.compile(r"^- Direct supers:\s+(.+)$")
TICK = re.compile(r"`([^`]+)`")
VALUE_FENCE = re.compile(r"^```")

# Defstruct-companion line scrapers. Each captures a single backticked symbol
# (NIL means the option was suppressed; we filter that out before resolving).
STRUCT_DEFAULT_CTOR = re.compile(r"^\*\*Default constructor:\*\*\s+`([^`]+)`")
STRUCT_PREDICATE = re.compile(r"^\*\*Predicate:\*\*\s+`([^`]+)`")
STRUCT_COPIER = re.compile(r"^\*\*Copier:\*\*\s+`([^`]+)`")
# `**All constructors:**` may span multiple lines (BOA constructors with slot
# lists). Match the first line; we accumulate text until we see the closing
# backtick.
STRUCT_ALL_CTORS_HEAD = re.compile(r"^\*\*All constructors:\*\*\s+`(.*)$")
STRUCT_SLOTS_HEADER = re.compile(r"^##\s+Slots\s*$")
# Slot table row: 4th column is the accessor (backticked symbol or `nil`).
STRUCT_SLOT_ROW = re.compile(r"^\|\s*[^|]+\|\s*[^|]+\|\s*[^|]+\|\s*([^|]+?)\s*\|")
# Slot table row: 1st column is the slot name (used by slot_types.csv
# validation — checking that a curated slot actually exists on the struct).
STRUCT_SLOT_NAME_ROW = re.compile(r"^\|\s*([^|]+?)\s*\|")
# Inside the All-constructors blob: any package-qualified or bare `make-…`
# symbol. Case-insensitive (sb-kernel prints constructor names lowercase via
# `~(~s~)`, but we match either form for safety).
STRUCT_MAKE_REF = re.compile(
    r"\b((?:[A-Za-z0-9/_+*-]+::?)?make-[A-Za-z0-9/_+*-]+)\b",
    re.IGNORECASE,
)
# Symbol mention inside a value block, e.g. ICHIRAN/DICT::ABBR-II
SYMBOL_REF = re.compile(r"ICHIRAN(?:/[A-Z0-9-]+)?::?[A-Z0-9*+/_-]+")

KIND_MAP = {"defun": "fn", "defmacro": "macro", "defgeneric": "gf"}

# Suffix → kind label written into symbols.csv. Order matters for
# longest-match (none collide here, but keep explicit for clarity).
SUFFIX_KIND = [
    ("_struct.md", "struct"),
    ("_class.md", "class"),
    ("_dao.md", "dao"),
    ("_global.md", "global"),
    ("_type.md", "type"),
    ("_condition.md", "condition"),
]


def fqn(package: str, name: str) -> str:
    return f"{package}:{name}"


def split_dep(token: str) -> tuple[str, str]:
    """`ichiran/characters:test-word` or `ichiran::strings` → (package, name)."""
    if "::" in token:
        pkg, _, name = token.partition("::")
    else:
        pkg, _, name = token.partition(":")
    return pkg, name


def normalise_dep(token: str) -> str:
    """Lowercase the package and name for consistent CSV joining."""
    pkg, name = split_dep(token.strip("`"))
    return fqn(pkg.lower(), name.lower())


def aux_kind(path: Path) -> str | None:
    name = path.name
    for suffix, kind in SUFFIX_KIND:
        if name.endswith(suffix):
            return kind
    return None


SECTION_HEADER = re.compile(r"^##\s+")
INPUTS_HEADER = re.compile(r"^##\s+Inputs\b")
OUTPUTS_HEADER = re.compile(r"^##\s+Outputs\b")
DECLARED_FTYPE = re.compile(r"^Declared ftype:\s*`(.+)`\s*$", re.DOTALL)
DOCSTRING_LINE = re.compile(r"^Docstring:\s*(.+)$", re.DOTALL)


def collect_section(lines: list[str], header_idx: int) -> str:
    """Return the section body (lines after `## Header`, up to the next `## `),
    joined with newlines and stripped."""
    j = header_idx + 1
    body: list[str] = []
    while j < len(lines) and not SECTION_HEADER.match(lines[j]):
        body.append(lines[j])
        j += 1
    return "\n".join(body).strip()


def collapse_ws(s: str) -> str:
    return re.sub(r"\s+", " ", s).strip()


def parse_signature(raw_lines: list[str]) -> dict | None:
    """Extract the lambda list / declared ftype / docstring from an md file.

    Returns a dict with keys `lambda_list` (str | None), `ftype` (str | None),
    `docstring` (str | None), or `None` if the md file has no signature
    sections at all (struct / class / dao / global / type / condition).

    Whitespace inside the lambda list and ftype is collapsed to single spaces
    so the output is byte-stable across re-runs of the introspector.
    """
    lambda_list: str | None = None
    ftype: str | None = None
    docstring: str | None = None

    for i, line in enumerate(raw_lines):
        if INPUTS_HEADER.match(line):
            body = collect_section(raw_lines, i)
            if body.startswith("`") and body.endswith("`") and len(body) > 1:
                lambda_list = collapse_ws(body[1:-1])
        elif OUTPUTS_HEADER.match(line):
            body = collect_section(raw_lines, i)
            m = DECLARED_FTYPE.match(body)
            if m:
                ftype = collapse_ws(m.group(1))
            else:
                m = DOCSTRING_LINE.match(body)
                if m:
                    docstring = collapse_ws(m.group(1))

    if lambda_list is None and ftype is None and docstring is None:
        return None
    return {"lambda_list": lambda_list, "ftype": ftype, "docstring": docstring}


def _norm_companion(token: str, package: str) -> str | None:
    """Normalize one defstruct-companion symbol (constructor / predicate /
    copier / accessor) to a lowercased FQN. Returns None for NIL / blank
    (suppressed options) so the caller can skip them."""
    n = token.strip().strip("`").strip()
    if not n or n.upper() == "NIL":
        return None
    if "::" in n or ":" in n:
        return normalise_dep(n)
    return normalise_dep(f"{package}:{n}")


def parse_struct_spawned(raw_lines: list[str], package: str) -> list[str]:
    """Extract every symbol the defstruct *spawns* (default + BOA
    constructors, predicate, copier, slot accessors).

    Returns deduplicated FQNs in declaration order. Used to synthesize
    `companion → struct` edges that SBCL's source-walker can't produce
    on its own (the bodies of these compiler-generated fns aren't visible
    to `function-lambda-expression`)."""
    out: list[str] = []
    seen: set[str] = set()

    def add(fq: str | None) -> None:
        if fq is not None and fq not in seen:
            seen.add(fq)
            out.append(fq)

    in_all_ctors = False
    all_ctors_buf: list[str] = []
    in_slots = False

    for line in raw_lines:
        if in_all_ctors:
            all_ctors_buf.append(line)
            if "`" in line:
                in_all_ctors = False
            continue

        m = STRUCT_DEFAULT_CTOR.match(line)
        if m:
            add(_norm_companion(m.group(1), package))
            continue
        m = STRUCT_PREDICATE.match(line)
        if m:
            add(_norm_companion(m.group(1), package))
            continue
        m = STRUCT_COPIER.match(line)
        if m:
            add(_norm_companion(m.group(1), package))
            continue
        m = STRUCT_ALL_CTORS_HEAD.match(line)
        if m:
            head = m.group(1)
            all_ctors_buf.append(head)
            # The head line may already contain the closing backtick.
            if "`" in head:
                in_all_ctors = False
            else:
                in_all_ctors = True
            continue

        if STRUCT_SLOTS_HEADER.match(line):
            in_slots = True
            continue
        if in_slots:
            if line.startswith("##"):
                in_slots = False
            else:
                m = STRUCT_SLOT_ROW.match(line)
                if m:
                    cell = m.group(1).strip()
                    if cell.lower() in ("accessor", "---"):
                        continue
                    add(_norm_companion(cell, package))

    # Pick every `make-…` reference out of the (possibly multi-line)
    # All-constructors blob. Catches BOA constructors that aren't in the
    # `Default constructor:` line, e.g. conjugation-rule's
    # `make-conjugation-rule` is declared via `:constructor make-X (...)`
    # with `:default` suppressed.
    blob = "\n".join(all_ctors_buf)
    for m in STRUCT_MAKE_REF.finditer(blob):
        add(_norm_companion(m.group(1), package))

    return out


CLASS_SLOTS_HEADER = re.compile(r"^##\s+Direct slots\s*$")
DAO_SLOTS_HEADER = re.compile(r"^##\s+Columns\s*$")
SLOT_TABLE_TOKEN = re.compile(r"[A-Za-z0-9/_+*-]+")


def parse_class_companions(raw_lines: list[str], package: str) -> list[str]:
    """Extract every symbol the defclass / dao slot options name as a
    reader, writer, or accessor. From a `_class.md` slot table (6 columns:
    name, initform, allocation, initargs, readers, writers) or a `_dao.md`
    columns table (5 columns: name, column, type, initargs, readers).

    The reader / writer cells are printed as `(SYMBOL)` or `(S1 S2 ...)`
    or `((SETF SYMBOL))` for `:accessor` slots, or `NIL` when no
    reader/writer was generated. We extract every non-`NIL`,
    non-`SETF` symbol token and qualify it against `package`.

    Returns deduplicated FQNs in declaration order. The caller treats
    these the same as struct-spawned companions: each one resolves to
    the parent class/dao, and gets dropped from `symbols.csv` because
    porting the parent satisfies them."""
    out: list[str] = []
    seen: set[str] = set()
    in_slots = False
    saw_separator = False

    for line in raw_lines:
        if CLASS_SLOTS_HEADER.match(line) or DAO_SLOTS_HEADER.match(line):
            in_slots = True
            saw_separator = False
            continue
        if not in_slots:
            continue
        if line.startswith("##"):
            in_slots = False
            continue
        if not line.startswith("|"):
            continue
        cols = [c.strip() for c in line.strip("|").split("|")]
        if not cols:
            continue
        first = cols[0]
        if first.lower() == "name":
            saw_separator = True
            continue
        if not saw_separator or set(first) <= {"-", ":"}:
            continue
        # Readers always at column index 4; writers at 5 if present (class only).
        cells_to_scan: list[str] = []
        if len(cols) > 4:
            cells_to_scan.append(cols[4])
        if len(cols) > 5:
            cells_to_scan.append(cols[5])
        for cell in cells_to_scan:
            for tok in SLOT_TABLE_TOKEN.findall(cell):
                if tok.upper() in ("NIL", "SETF"):
                    continue
                fq = _norm_companion(tok, package)
                if fq and fq not in seen:
                    seen.add(fq)
                    out.append(fq)
    return out


def parse_slot_names(raw_lines: list[str]) -> set[str]:
    """Extract slot NAMES (first column of the slot table) from a
    `_struct.md`, `_class.md`, or `_dao.md` file. Used by the
    slot_types.csv validation pass to catch typos: a curated slot must
    actually exist on its owning type.

    Both kinds of slot table use a markdown table whose first column is
    the slot name; the table headers differ (`## Slots` vs.
    `## Direct slots`), but the row format is identical."""
    names: set[str] = set()
    in_slots = False
    saw_header_separator = False
    for line in raw_lines:
        if STRUCT_SLOTS_HEADER.match(line) or CLASS_SLOTS_HEADER.match(line):
            in_slots = True
            saw_header_separator = False
            continue
        if not in_slots:
            continue
        if line.startswith("##"):
            in_slots = False
            continue
        m = STRUCT_SLOT_NAME_ROW.match(line)
        if not m:
            continue
        cell = m.group(1).strip()
        # Skip the header row (`name`) and the markdown separator (`---`).
        if cell.lower() == "name":
            saw_header_separator = True
            continue
        if not saw_header_separator or set(cell) <= {"-", ":"}:
            continue
        names.add(cell.lower())
    return names


def parse_slot_types_csv(by_fqn: dict[str, dict],
                         struct_slots: dict[str, set[str]]) -> list[tuple[str, str]]:
    """Read slot_types.csv (hand-curated) and return validated
    `(struct_fqn, target_fqn)` edges with origin `slot-type`.

    Each row asserts: defstruct STRUCT_FQN's SLOT holds a value of type
    TARGET_FQN, so the struct definition depends on TARGET_FQN even
    though the SBCL introspector reports the slot's type as `t`.

    Validation (fatal — exits non-zero on any failure, since silent
    drops mask typos):
      - struct_fqn must exist in symbols.csv and be a slot-bearing kind
        (struct, class, or dao)
      - target_fqn must exist in symbols.csv
      - slot must be a real slot of struct_fqn (per its `_<kind>.md`)
      - no self-edges
    """
    if not SLOT_TYPES_CSV.exists():
        return []

    edges: list[tuple[str, str]] = []
    errors: list[str] = []
    seen: set[tuple[str, str, str]] = set()

    with SLOT_TYPES_CSV.open(encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        required = {"struct_fqn", "slot", "target_fqn"}
        if not required.issubset(reader.fieldnames or ()):
            print(
                f"slot_types.csv: missing required columns "
                f"(have {reader.fieldnames}, need {sorted(required)})",
                file=sys.stderr,
            )
            return []
        for row_num, row in enumerate(reader, start=2):
            struct_fqn = (row.get("struct_fqn") or "").strip().lower()
            slot       = (row.get("slot")       or "").strip().lower()
            target_fqn = (row.get("target_fqn") or "").strip().lower()
            if not struct_fqn or not slot or not target_fqn:
                errors.append(
                    f"row {row_num}: blank struct_fqn / slot / target_fqn"
                )
                continue
            key = (struct_fqn, slot, target_fqn)
            if key in seen:
                errors.append(f"row {row_num}: duplicate {struct_fqn}.{slot} → {target_fqn}")
                continue
            seen.add(key)
            if struct_fqn == target_fqn:
                errors.append(f"row {row_num}: self-edge {struct_fqn}.{slot}")
                continue
            if struct_fqn not in by_fqn:
                errors.append(f"row {row_num}: unknown struct_fqn '{struct_fqn}'")
                continue
            if by_fqn[struct_fqn]["kind"] not in ("struct", "class", "dao"):
                errors.append(
                    f"row {row_num}: struct_fqn '{struct_fqn}' is "
                    f"kind={by_fqn[struct_fqn]['kind']}, expected struct/class/dao"
                )
                continue
            if target_fqn not in by_fqn:
                errors.append(f"row {row_num}: unknown target_fqn '{target_fqn}'")
                continue
            real_slots = struct_slots.get(struct_fqn, set())
            if real_slots and slot not in real_slots:
                errors.append(
                    f"row {row_num}: '{struct_fqn}' has no slot "
                    f"'{slot}' (slots: {sorted(real_slots)})"
                )
                continue
            edges.append((struct_fqn, target_fqn))

    if errors:
        print("slot_types.csv validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  {e}", file=sys.stderr)
        sys.exit(1)

    return edges


def parse_value_block_deps(lines: list[str], start_idx: int) -> list[str]:
    """From a ```lisp fenced block, extract every ICHIRAN-package symbol
    reference inside. Returns lowercased FQNs."""
    deps: list[str] = []
    i = start_idx + 1
    while i < len(lines):
        if VALUE_FENCE.match(lines[i]):
            break
        for m in SYMBOL_REF.finditer(lines[i]):
            deps.append(normalise_dep(m.group(0)))
        i += 1
    return deps


def parse_md_header(raw_lines: list[str]) -> tuple[str | None, str | None, str | None, int, str | None]:
    """Parse H1 / Package / Source / Definition-form lines from an md file.

    Returns (name, package, source_file, line_no, kind_field). Any field
    that wasn't found is None (line_no defaults to 0). Used by both
    `parse_md` (which then resolves dependencies) and the signatures
    extractor (which only needs the symbol identity).
    """
    name = package = source_file = kind_field = None
    line_no = 0
    for line in raw_lines:
        if name is None:
            m = H1.match(line)
            if m:
                name = m.group(1).strip()
                continue
        if package is None:
            m = PACKAGE.match(line)
            if m:
                package = m.group(1)
                continue
        if source_file is None:
            m = SOURCE.match(line)
            if m:
                source_file = m.group(1)
                line_no = int(m.group(2)) if m.group(2) else 0
                continue
        if kind_field is None:
            m = DEFFORM.match(line)
            if m:
                kind_field = KIND_MAP.get(m.group(1), m.group(1))
                continue
    return name, package, source_file, line_no, kind_field


def parse_md(path: Path) -> tuple[dict, list[str], list[str], list[str], set[str]] | None:
    """Returns ({symbol-row}, [runtime-deps], [source-walk-deps],
    [structural-spawned], {slot-names}) or None.

    `structural-spawned` is non-empty only for `_struct.md` rows: it lists the
    FQNs the defstruct generates (constructor, predicate, copier, accessors).
    The caller inverts them into `spawned → struct` edges with origin
    'structural', because the spawned fns have no walkable body for
    `function-lambda-expression` to surface a dep on the struct.

    `slot-names` is non-empty only for `_struct.md` rows: it carries the
    lowercased slot names so `parse_slot_types_csv` can validate that
    each curated edge cites a real slot."""
    raw_lines = path.read_text(encoding="utf-8").splitlines()
    deps: list[str] = []
    source_walk_deps: list[str] = []
    structural_spawned: list[str] = []
    slot_names: set[str] = set()
    in_deps = False

    suffix_kind = aux_kind(path)
    name, package, source_file, line_no, kind_field = parse_md_header(raw_lines)

    if not (name and package):
        return None

    # Second pass: dependency extraction (kind-specific).
    if suffix_kind is None:
        # Functions / macros / generics: two sections.
        # `## Dependencies` is the runtime call-graph (precise per-method when
        # nested under `### method (...)`).
        # `## Source-walked references` is the source-walk pass — catches DAO
        # class symbols and other data references invisible to the call graph.
        in_source_walk = False
        for line in raw_lines:
            if DEP_HEADER.match(line):
                in_deps, in_source_walk = True, False
                continue
            if SOURCE_WALK_HEADER.match(line):
                in_deps, in_source_walk = False, True
                continue
            if in_deps or in_source_walk:
                if line.startswith("## "):
                    in_deps = in_source_walk = False
                    continue
                m = DEP.match(line)
                if m:
                    target = source_walk_deps if in_source_walk else deps
                    target.append(normalise_dep(m.group(1)))
        kind_out = kind_field or ""
    elif suffix_kind in ("struct",):
        for line in raw_lines:
            m = INCLUDE.match(line)
            if m and m.group(1).strip().upper() != "NIL":
                # Bare struct name, e.g. `SOMETHING` — assume same package.
                inc = m.group(1).strip()
                deps.append(normalise_dep(f"{package}:{inc}"))
                break
        structural_spawned = parse_struct_spawned(raw_lines, package)
        slot_names = parse_slot_names(raw_lines)
        kind_out = "struct"
    elif suffix_kind in ("class", "dao"):
        for line in raw_lines:
            m = SUPERS.match(line)
            if m:
                # Pull each backticked symbol; superclasses can be
                # bare (same-package) or fully-qualified.
                for tok in TICK.findall(m.group(1)):
                    if tok.upper() == "STANDARD-OBJECT" or tok.lower() == "_(none)_":
                        continue
                    if ":" in tok:
                        deps.append(normalise_dep(tok))
                    else:
                        deps.append(normalise_dep(f"{package}:{tok}"))
                break
        structural_spawned = parse_class_companions(raw_lines, package)
        slot_names = parse_slot_names(raw_lines)
        kind_out = suffix_kind
    elif suffix_kind == "global":
        # Find the ```lisp fence and walk for symbol references.
        for idx, line in enumerate(raw_lines):
            if VALUE_FENCE.match(line) and "lisp" in line:
                deps.extend(parse_value_block_deps(raw_lines, idx))
                break
        kind_out = "global"
    elif suffix_kind == "type":
        # The single deftype in the codebase has no ichiran-symbol deps;
        # walking the value block harmlessly returns nothing.
        for idx, line in enumerate(raw_lines):
            if VALUE_FENCE.match(line) and "lisp" in line:
                deps.extend(parse_value_block_deps(raw_lines, idx))
                break
        kind_out = "type"
    elif suffix_kind == "condition":
        for line in raw_lines:
            m = INHERITS.match(line)
            if m and m.group(1).upper() != "ERROR":
                deps.append(normalise_dep(f"{package}:{m.group(1).strip()}"))
                break
        kind_out = "condition"
    else:
        kind_out = suffix_kind

    # Source-walked references can appear on any md kind — the introspector
    # emits the section for fn/macro/gf, classes/structs/daos/conditions, and
    # globals (the last specifically catches DSL-defined globals like
    # *counter-cache* / *special-counters* whose populator body the call-graph
    # pass can't see). The kind-specific branches above don't consume this
    # section, so we run a unified parse here for kinds that didn't already.
    if suffix_kind is not None:
        in_source_walk = False
        for line in raw_lines:
            if SOURCE_WALK_HEADER.match(line):
                in_source_walk = True
                continue
            if in_source_walk:
                if line.startswith("## "):
                    in_source_walk = False
                    continue
                m = DEP.match(line)
                if m:
                    source_walk_deps.append(normalise_dep(m.group(1)))

    # For defstructs, the source-walker can pick up the constructor / predicate /
    # copier names when they're explicitly written in the `:constructor make-X
    # (...)` / `:predicate ...` / `:copier ...` options, producing `struct →
    # companion` edges that are inverted relative to what the port plan needs.
    # Drop those — the structural pass writes the correct direction.
    if structural_spawned:
        spawn_set = set(structural_spawned)
        source_walk_deps = [d for d in source_walk_deps if d not in spawn_set]
        deps = [d for d in deps if d not in spawn_set]

    return (
        {
            "fqn": fqn(package, name),
            "name": name,
            "package": package,
            "file": source_file or "",
            "line": line_no,
            "kind": kind_out,
            "status": "pending",
            "reason": "",
            "extracted": "",
            "audited": "",
        },
        deps,
        source_walk_deps,
        structural_spawned,
        slot_names,
    )


def extract_signatures(md_files: list[Path]) -> dict[str, dict]:
    """Walk md files and pull the lambda list / declared ftype / docstring
    for every fn / macro / gf. Skips kinds that have no callable surface
    (struct / class / dao / global / type / condition).

    Keyed by FQN as derived from the md file's Package + H1 fields. Note:
    the FQN can be wrong if the introspector mislabeled a symbol's package
    (see the `not-a-number` case noted in the gate at __main__) — but that
    bug only affects non-fn kinds, which are skipped here, so signatures.json
    is unpoisoned.
    """
    sigs: dict[str, dict] = {}
    for path in md_files:
        raw_lines = path.read_text(encoding="utf-8").splitlines()
        name, package, source_file, line_no, kind_field = parse_md_header(raw_lines)
        if not (name and package):
            continue
        suffix_kind = aux_kind(path)
        kind = suffix_kind or (kind_field or "")
        sig = parse_signature(raw_lines)
        if sig is None:
            continue
        key = fqn(package, name)
        sigs[key] = {
            "name": name,
            "package": package,
            "file": source_file or "",
            "line": line_no,
            "kind": kind,
            **sig,
        }
    return sigs


def write_signatures(sigs: dict[str, dict]) -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    # Sort keys for byte-stable output across runs.
    payload = {k: sigs[k] for k in sorted(sigs)}
    SIGNATURES_JSON.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def signatures_only() -> int:
    md_files = sorted(REVERSE_DIR.glob("*.lisp/*.md"))
    if not md_files:
        print(f"no md files under {REVERSE_DIR}", file=sys.stderr)
        return 1
    sigs = extract_signatures(md_files)
    write_signatures(sigs)
    rel = lambda p: os.path.relpath(p, REVERSE_DIR.parent)
    print(f"signatures: {len(sigs)} -> {rel(SIGNATURES_JSON)}")
    return 0


def main() -> int:
    # Sort kind-suffixed mds (class/struct/dao/global/type/condition)
    # before bare-name (fn/gf/macro) mds, so on FQN collision (e.g. an
    # auto-gen `:reader X` on a class also named X — the slot reader and
    # the class share the FQN `<pkg>:X`) the typed kind wins. The gf
    # version is then either folded as a companion or silently
    # dropped — the class is the canonical home for that FQN.
    def _md_sort_key(p: Path):
        name = p.name
        is_typed = any(name.endswith(suf) for suf, _ in SUFFIX_KIND)
        return (0 if is_typed else 1, name)
    md_files = sorted(REVERSE_DIR.glob("*.lisp/*.md"), key=_md_sort_key)
    if not md_files:
        print(f"no md files under {REVERSE_DIR}", file=sys.stderr)
        return 1

    rows: list[dict] = []
    runtime_pending: list[tuple[str, str]] = []
    source_pending: list[tuple[str, str]] = []
    structural_pending: list[tuple[str, str]] = []
    struct_slots: dict[str, set[str]] = {}
    seen: set[str] = set()

    for path in md_files:
        parsed = parse_md(path)
        if parsed is None:
            print(f"skip (no header): {path}", file=sys.stderr)
            continue
        sym, deps, swdeps, spawned, slot_names = parsed
        # If the same fqn appears via both a function md and a struct md
        # (e.g. autogenerated accessor + struct itself collide), keep the
        # first one encountered alphabetically and warn. In practice the
        # struct/class fqns are distinct from their accessor fqns so this
        # only fires on real duplicates.
        if sym["fqn"] in seen:
            print(
                f"duplicate fqn: {sym['fqn']} (skipping {path.name})",
                file=sys.stderr,
            )
            continue
        seen.add(sym["fqn"])
        rows.append(sym)
        for dep in deps:
            runtime_pending.append((sym["fqn"], dep))
        for dep in swdeps:
            source_pending.append((sym["fqn"], dep))
        # Structural edges run companion → struct. The defstruct itself is
        # `sym["fqn"]`, the spawned companions are `spawned`.
        for spawn in spawned:
            structural_pending.append((spawn, sym["fqn"]))
        if slot_names:
            struct_slots[sym["fqn"]] = slot_names

    # Build the companion → parent map across every parsed defstruct /
    # defclass / dao md. The companions (constructor / predicate / copier /
    # accessors for structs; slot readers / writers for classes / daos)
    # are auto-generated by the parent's defining form and have no
    # standalone porting work — porting the parent struct/class as a
    # Rust `pub struct` (with `pub` field access) satisfies all of them
    # at once. Modeling them as separate graph nodes breaks the
    # leaf-up topo-sort invariant: a caller of `make-segment` shows up
    # in the plan with a "pending" dep that will never flip on its own.
    #
    # Per-parent self-mapping (e.g. `:reader top-array` on the
    # top-array class shares the FQN `ichiran/dict:top-array` with
    # the class itself) gets skipped — the parent's own row must
    # survive.
    companion_claims: dict[str, set[str]] = {}
    for caller, parent_fqn in structural_pending:
        if caller == parent_fqn:
            continue
        companion_claims.setdefault(caller, set()).add(parent_fqn)

    # Fold a companion ONLY when exactly one class/struct/dao claims
    # it. Multi-parent claims indicate a polymorphic gf (e.g. `text`
    # is a `:reader` on proxy-text, compound-text, kanji-text,
    # kana-text, conj-source-reading, restricted-readings, sense-prop,
    # gloss — eight parents — plus an explicit defmethod override on
    # counter-text). Polymorphic gfs are real dispatch surfaces, not
    # bare accessors; keep them as standalone graph nodes so callers
    # can depend on them and the Rust port has a single dispatch site.
    companion_to_parent: dict[str, str] = {
        c: next(iter(p)) for c, p in companion_claims.items() if len(p) == 1
    }

    # Drop companion rows. Their data lives entirely in the parent's
    # md file (the slot table, the constructor / predicate / copier
    # lines); the standalone fn md adds nothing the port needs.
    companion_rows_dropped = sum(1 for r in rows if r["fqn"] in companion_to_parent)
    rows = [r for r in rows if r["fqn"] not in companion_to_parent]

    def _rewrite_callee(fqn: str) -> str:
        return companion_to_parent.get(fqn, fqn)

    def _rewrite_pairs(pairs: list[tuple[str, str]]) -> list[tuple[str, str]]:
        out: list[tuple[str, str]] = []
        for caller, callee in pairs:
            # Companion as caller: drop. The structural edges
            # (companion → parent) survive only for catalog purposes;
            # with the companion gone, the edge has no source node.
            if caller in companion_to_parent:
                continue
            new_callee = _rewrite_callee(callee)
            if new_callee == caller:
                # Self-edge after rewrite (e.g. struct → struct via its
                # own accessor): drop.
                continue
            out.append((caller, new_callee))
        return out

    runtime_pending  = _rewrite_pairs(runtime_pending)
    source_pending   = _rewrite_pairs(source_pending)
    structural_pending = _rewrite_pairs(structural_pending)

    by_fqn = {r["fqn"]: r for r in rows}

    # Slot-type edges (struct → target) — hand-curated in slot_types.csv to
    # repair the introspector's blindspot for `t`-typed defstruct slots.
    # Validation aborts the run if any row is malformed; see CSV header.
    slot_type_edges = parse_slot_types_csv(by_fqn, struct_slots)

    # Source-walk over-collects (locals, lambda-list params, slot names).
    # Drop callees that aren't a known top-level definition. Self-edges
    # (introspector also filters them but belt-and-suspenders) get dropped.
    source_filtered: list[tuple[str, str]] = []
    source_dropped = 0
    for caller, callee in source_pending:
        if callee not in by_fqn or callee == caller:
            source_dropped += 1
            continue
        source_filtered.append((caller, callee))

    # Structural edges (companion → struct) — drop any that point at an
    # unknown caller (companion might be filtered out of the universe by
    # has-any-definition-p) or that are self-referential.
    structural_filtered: list[tuple[str, str]] = []
    structural_dropped = 0
    for caller, callee in structural_pending:
        if caller not in by_fqn or caller == callee:
            structural_dropped += 1
            continue
        structural_filtered.append((caller, callee))

    # Union with origin tagging. Structural and slot-type edges win over
    # runtime / source tags — they describe relationships (companion → owner,
    # struct → contained-type) the other passes can't see, and we want them
    # surfaced explicitly in the `origin` column for traceability.
    runtime_set = set(runtime_pending)
    source_set = set(source_filtered)
    structural_set = set(structural_filtered)
    slot_type_set = set(slot_type_edges)
    edges: list[tuple[str, str, int, str]] = []
    unresolved: set[str] = set()
    seen_pairs: set[tuple[str, str]] = set()
    runtime_only = 0
    source_only = 0
    structural_only = 0
    slot_type_only = 0
    both_count = 0
    for caller, callee in sorted(runtime_set | source_set | structural_set | slot_type_set):
        if (caller, callee) in seen_pairs:
            continue
        seen_pairs.add((caller, callee))
        in_structural = (caller, callee) in structural_set
        in_slot_type = (caller, callee) in slot_type_set
        in_runtime = (caller, callee) in runtime_set
        in_source = (caller, callee) in source_set
        if in_structural:
            origin = "structural"
            structural_only += 1
        elif in_slot_type:
            origin = "slot-type"
            slot_type_only += 1
        elif in_runtime and in_source:
            origin = "both"
            both_count += 1
        elif in_source:
            origin = "source"
            source_only += 1
        else:
            origin = "runtime"
            runtime_only += 1
        resolved = 1 if callee in by_fqn else 0
        if not resolved:
            unresolved.add(callee)
        edges.append((caller, callee, resolved, origin))

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # Preserve all four state columns across rebuilds. `status` / `reason`
    # are porter progress, `extracted` / `audited` are pipeline workstream
    # state — none of them are introspector output, so none of them have
    # any reason to reset just because the graph regenerated. Symbols that
    # disappear lose their state (no row to hold it); new symbols start
    # with the parse_md defaults (status='pending', the rest blank).
    prior_state: dict[str, dict[str, str]] = {}
    if SYMBOLS_CSV.exists():
        with SYMBOLS_CSV.open(encoding="utf-8") as fh:
            for r in csv.DictReader(fh):
                prior_state[r["fqn"]] = {
                    "status":    r.get("status", "")    or "pending",
                    "reason":    r.get("reason", "")    or "",
                    "extracted": r.get("extracted", "") or "",
                    "audited":   r.get("audited", "")   or "",
                }

    fieldnames = [
        "fqn", "name", "package", "file", "line", "kind",
        "status", "reason", "extracted", "audited",
    ]
    with SYMBOLS_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=fieldnames)
        w.writeheader()
        for r in sorted(rows, key=lambda r: r["fqn"]):
            prior = prior_state.get(r["fqn"], {})
            r["status"]    = prior.get("status",    "pending")
            r["reason"]    = prior.get("reason",    "")
            r["extracted"] = prior.get("extracted", "")
            r["audited"]   = prior.get("audited",   "")
            w.writerow(r)

    with EDGES_CSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["caller_fqn", "callee_fqn", "resolved", "origin"])
        for row in sorted(edges):
            w.writerow(row)

    sigs = extract_signatures(md_files)
    # Drop companion entries — they share the parent's signature only
    # by accident (auto-gen accessor takes the struct instance as its
    # one argument), and audit-signatures iterates symbols.csv, so a
    # leftover signature for a removed companion is dead weight.
    sigs = {k: v for k, v in sigs.items() if k not in companion_to_parent}
    write_signatures(sigs)

    rel = lambda p: os.path.relpath(p, REVERSE_DIR.parent)
    print(f"symbols: {len(rows)} -> {rel(SYMBOLS_CSV)}")
    print(f"edges:   {len(edges)} -> {rel(EDGES_CSV)}")
    print(f"signatures: {len(sigs)} -> {rel(SIGNATURES_JSON)}")
    print(
        f"  origin: runtime={runtime_only}, source={source_only}, "
        f"structural={structural_only}, slot-type={slot_type_only}, "
        f"both={both_count} "
        f"(source-walk dropped {source_dropped} non-top-level / self refs; "
        f"structural dropped {structural_dropped}; "
        f"companions folded into parents: {len(companion_to_parent)} "
        f"(rows removed: {companion_rows_dropped}))"
    )
    if unresolved:
        print(f"unresolved callees: {len(unresolved)} (external / built-in)")

    # Per-kind breakdown for sanity.
    from collections import Counter
    kinds = Counter(r["kind"] for r in rows)
    print(
        "by kind: "
        + ", ".join(f"{k}={n}" for k, n in sorted(kinds.items(), key=lambda x: -x[1]))
    )
    return 0


if __name__ == "__main__":
    if "--signatures-only" in sys.argv[1:]:
        sys.exit(signatures_only())
    sys.exit(main())
