//! Port of `ichiran/dict:conj-data-prop` (`dict.lisp:325`).
//!
//! Slot accessor generated by `(defstruct conj-data seq from via prop
//! src-map)` for the `prop` field. Returns the `conj-prop` slot of a
//! [`super::conj_data_struct::ConjData`] — possibly `NIL` per the
//! struct's nil-defaulted slots — by clone since callers consume the
//! row as their own value.

use super::conj_data_struct::ConjData;
use super::conj_prop_dao::ConjProp;

pub fn conj_data_prop(cd: &ConjData) -> Option<ConjProp> {
    cd.prop.clone()
}
