//! Port of `ichiran/dict:conj-data-from` (`dict.lisp:325`).
//!
//! Slot accessor generated by `(defstruct conj-data seq from via prop
//! src-map)` for the `from` field. Returns the seq id of the source
//! entry the conjugation derives from — possibly `NIL` per the
//! struct's nil-defaulted slots.

use super::conj_data_struct::ConjData;

pub fn conj_data_from(cd: &ConjData) -> Option<i32> {
    cd.from
}
