//! Port of `ichiran/dict:make-conj-data` (`dict.lisp:325`).
//!
//! Constructor function generated by `(defstruct conj-data seq from
//! via prop src-map)`. The Lisp lambda list is
//! `(&key seq from via prop src-map)` with every default `NIL`; the
//! Rust port keeps the `&key`-shaped surface as positional `Option`
//! arguments matching the slot defaults on
//! [`super::conj_data_struct::ConjData`]. Callers that omit a Lisp
//! keyword pass [`None`] for the same slot.

use super::conj_data_struct::ConjData;
use super::conj_prop_dao::ConjProp;

pub fn make_conj_data(
    seq: Option<i32>,
    from: Option<i32>,
    via: Option<i32>,
    prop: Option<ConjProp>,
    src_map: Vec<(String, String)>,
) -> ConjData {
    ConjData { seq, from, via, prop, src_map }
}
